### ISSUE TITLE
Version tracking issue: 2.0.0

### ISSUE THREAD

**Issue by shortercode** [nanoporetech/ts-extended-types#7]
# Planned Breaking Changes
- [x] #3 Rename asRecord to asDictionary.
- [x] #6 Change asRecordRecursive to take a Type Assert function, and to return the original unmodified object.
# Planned Additions
- [x] #5 Add isUnion function.
- [x] #4 Add isRecordRecursive and isArrayRecursive functions.
